import { ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder } from 'discord.js';
import { characters } from '../data/characters.js';
import { weapons } from '../data/weapons.js';
import { domains } from '../data/domains.js';
import { currentActor, validTargets } from '../game/battle.js';
import { characterPower, calculatePlayerPower } from '../game/stats.js';

export const cid=(userId,action,arg='')=>`nls|${userId}|${action}|${arg}`;
const btn=(userId,action,label,style=ButtonStyle.Secondary,emoji,arg='',disabled=false)=>{const b=new ButtonBuilder().setCustomId(cid(userId,action,arg)).setLabel(label).setStyle(style).setDisabled(disabled);if(emoji)b.setEmoji(emoji);return b;};

export function homeComponents(userId,player){
 const menu=new StringSelectMenuBuilder().setCustomId(cid(userId,'mainmenu')).setPlaceholder('Open Neverless RPG menu').addOptions([
  {label:'Wish',description:'Pull characters and weapons',value:'wish',emoji:'🌠'},
  {label:'Domains',description:'Fast battles, artifacts and clear records',value:'domains',emoji:'🏛️'},
  {label:'CPU Arena',description:'Practice team roles against AI',value:'cpu',emoji:'⚔️'},
  {label:'Characters',description:'Levels, talents, gear and showcase',value:'characters',emoji:'🧙'},
  {label:'Inventory',description:'View saved weapons and resources',value:'inventory',emoji:'🎒'},
  {label:'Artifacts',description:'View artifact collection',value:'artifacts',emoji:'🏺'},
  {label:'Upgrades',description:'Permanent account upgrades',value:'upgrades',emoji:'📈'},
 ]);
 const dailyReady=!player?.daily?.lastClaimAt || Date.now()-player.daily.lastClaimAt>=24*60*60*1000;
 return [new ActionRowBuilder().addComponents(menu),new ActionRowBuilder().addComponents(btn(userId,'daily',dailyReady?'Claim Daily':'Daily Claimed',ButtonStyle.Success,'🎁','',!dailyReady))];
}
export function profileRow(userId){return [new ActionRowBuilder().addComponents(btn(userId,'home','Profile',ButtonStyle.Primary,'👤'))];}

export function wishComponents(userId,banner='character',player){const primos=player?.primogems||0;return [
 new ActionRowBuilder().addComponents(btn(userId,'wishbanner','Character Banner',banner==='character'?ButtonStyle.Primary:ButtonStyle.Secondary,'🧙','character'),btn(userId,'wishbanner','Weapon Banner',banner==='weapon'?ButtonStyle.Primary:ButtonStyle.Secondary,'🗡️','weapon')),
 new ActionRowBuilder().addComponents(btn(userId,'wish','Wish x1 - 160',ButtonStyle.Success,'✨','1',primos<160),btn(userId,'wish','Wish x10 - 1600',ButtonStyle.Success,'🌠','10',primos<1600),btn(userId,'home','Profile',ButtonStyle.Secondary,'👤')),
];}

export function domainComponents(userId,player,session={}){
 const menu=new StringSelectMenuBuilder().setCustomId(cid(userId,'domainselect')).setPlaceholder('Choose a domain').addOptions(Object.values(domains).map((d,i)=>({label:i===0?`Starter - ${d.name}`:d.name,description:`Lv.${d.level} • PWR ${d.recommendedPower.toLocaleString()} • ${d.resin} Resin`,value:d.id,default:d.id===session.domainId})));
 const ids=Object.keys(player.characters).slice(0,25);const opts=ids.map(id=>({label:characters[id].name,description:`${characters[id].role} • ${characters[id].element} • Lv.${player.characters[id].level} • PWR ${characterPower(player,id)}`,value:id,default:(session.team||[]).includes(id)}));
 const team=new StringSelectMenuBuilder().setCustomId(cid(userId,'teamselect','domain')).setPlaceholder('Choose exactly 4 characters').setMinValues(Math.min(4,opts.length)).setMaxValues(Math.min(4,opts.length)).addOptions(opts);
 const d=session.domainId?domains[session.domainId]:null,prog=d?(player.domainProgress?.[d.id]||{clears:0}):{clears:0};const ready=Boolean(d&&(session.team||[]).length===4&&player.resin>=d.resin);const quick=Boolean(d&&prog.clears>0&&calculatePlayerPower(player)>=Math.ceil(d.recommendedPower*1.12)&&player.resin>=d.resin);
 return [new ActionRowBuilder().addComponents(menu),new ActionRowBuilder().addComponents(team),new ActionRowBuilder().addComponents(btn(userId,'startdomain','Start Domain',ButtonStyle.Success,'⚔️','',!ready),btn(userId,'quickdomain','Quick Clear',ButtonStyle.Primary,'⚡','',!quick),btn(userId,'home','Profile',ButtonStyle.Secondary,'👤'))];
}

export function cpuComponents(userId,player,session={}){const opts=Object.keys(player.characters).slice(0,25).map(id=>({label:characters[id].name,description:`${characters[id].role} • Lv.${player.characters[id].level} • PWR ${characterPower(player,id)}`,value:id,default:(session.team||[]).includes(id)}));const team=new StringSelectMenuBuilder().setCustomId(cid(userId,'teamselect','cpu')).setPlaceholder('Choose exactly 4 characters').setMinValues(Math.min(4,opts.length)).setMaxValues(Math.min(4,opts.length)).addOptions(opts);return [new ActionRowBuilder().addComponents(team),new ActionRowBuilder().addComponents(btn(userId,'startcpu','Start CPU Battle',ButtonStyle.Danger,'⚔️','',(session.team||[]).length!==4),btn(userId,'home','Profile',ButtonStyle.Secondary,'👤'))];}

export function characterComponents(userId,player){const ids=Object.keys(player.characters).slice(0,25);const inspect=new StringSelectMenuBuilder().setCustomId(cid(userId,'charinspect')).setPlaceholder('Inspect a character').addOptions(ids.map(id=>({label:characters[id].name,description:`${characters[id].role} • Lv.${player.characters[id].level} • PWR ${characterPower(player,id)}`,value:id})));const show=new StringSelectMenuBuilder().setCustomId(cid(userId,'showcaseselect')).setPlaceholder('Choose profile showcase').setMinValues(1).setMaxValues(Math.min(10,ids.length)).addOptions(ids.map(id=>({label:characters[id].name,description:`Show on profile • Lv.${player.characters[id].level}`,value:id,default:(player.showcase||[]).includes(id)})));return [new ActionRowBuilder().addComponents(inspect),new ActionRowBuilder().addComponents(show),...profileRow(userId)];}
export function characterDetailComponents(userId,charId){return [new ActionRowBuilder().addComponents(btn(userId,'levelchar','Level +1',ButtonStyle.Success,'⬆️',`${charId}:1`),btn(userId,'levelchar','Level +5',ButtonStyle.Success,'⏫',`${charId}:5`),btn(userId,'equipweaponchar','Weapon',ButtonStyle.Secondary,'🗡️',charId),btn(userId,'equipartifactchar','Artifact',ButtonStyle.Secondary,'🏺',charId)),new ActionRowBuilder().addComponents(btn(userId,'talent','Normal Talent',ButtonStyle.Secondary,'🗡️',`${charId}:normal`),btn(userId,'talent','Skill Talent',ButtonStyle.Primary,'✨',`${charId}:skill`),btn(userId,'talent','Burst Talent',ButtonStyle.Danger,'💥',`${charId}:burst`)),new ActionRowBuilder().addComponents(btn(userId,'open','Roster',ButtonStyle.Secondary,'📚','characters'),btn(userId,'home','Profile',ButtonStyle.Primary,'👤'))];}
export function weaponEquipComponents(userId,player,charId){const type=characters[charId].weaponType,opts=Object.keys(player.weapons).filter(id=>weapons[id]?.type===type).slice(0,25).map(id=>({label:weapons[id].name,description:`${weapons[id].rarity}★ • ${type} • Lv.${player.weapons[id].level}`,value:id}));const rows=[];if(opts.length)rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(cid(userId,'equipweapon',charId)).setPlaceholder(`Choose ${type}`).addOptions(opts)));rows.push(...profileRow(userId));return rows;}
export function artifactEquipComponents(userId,player,charId){const opts=Object.values(player.artifacts).slice(0,25).map(a=>({label:`${a.slot} • ${a.setId}`,description:`${a.rarity}★ +${a.level} • ${a.main.key}`,value:a.id}));const rows=[];if(opts.length)rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(cid(userId,'equipartifact',charId)).setPlaceholder('Choose artifact').addOptions(opts)));rows.push(...profileRow(userId));return rows;}
export function upgradeComponents(userId){return [new ActionRowBuilder().addComponents(btn(userId,'passive','ATK',ButtonStyle.Secondary,'⚔️','atk'),btn(userId,'passive','HP',ButtonStyle.Secondary,'❤️','hp'),btn(userId,'passive','CRIT Rate',ButtonStyle.Secondary,'🎯','critRate'),btn(userId,'passive','CRIT DMG',ButtonStyle.Secondary,'💥','critDmg'),btn(userId,'passive','SPD',ButtonStyle.Secondary,'💨','spd')),...profileRow(userId)];}

export function battleComponents(userId,battle,pending=null){const actor=currentActor(battle);if(!actor||battle.winner)return profileRow(userId);if(actor.side!=='player')return [new ActionRowBuilder().addComponents(btn(userId,'battlewait','CPU Turn',ButtonStyle.Secondary,'🤖'))];if(pending){const targets=validTargets(battle,pending).slice(0,25);const select=new StringSelectMenuBuilder().setCustomId(cid(userId,'battletarget',pending)).setPlaceholder('Choose target').addOptions(targets.map(t=>({label:t.name,description:`HP ${Math.round(t.hp)}/${t.maxHp}`,value:t.uid})));return [new ActionRowBuilder().addComponents(select),new ActionRowBuilder().addComponents(btn(userId,'battlecancel','Cancel',ButtonStyle.Secondary,'↩️'),btn(userId,'forfeit','Forfeit',ButtonStyle.Danger,'🏳️'))];}return [new ActionRowBuilder().addComponents(btn(userId,'battleaction',`Normal Lv.${actor.skills.normal?.talentLevel||1}`,ButtonStyle.Secondary,'🗡️','normal'),btn(userId,'battleaction',`Skill Lv.${actor.skills.skill?.talentLevel||1}`,actor.cooldowns.skill>0?ButtonStyle.Secondary:ButtonStyle.Primary,'✨','skill',actor.cooldowns.skill>0),btn(userId,'battleaction',`Burst Lv.${actor.skills.burst?.talentLevel||1}`,ButtonStyle.Danger,'💥','burst',actor.energy<(actor.skills.burst.cost||80)),btn(userId,'forfeit','Forfeit',ButtonStyle.Secondary,'🏳️'))];}
